### ISSUE TITLE
All tech trees broken except for the Specialized and Tactics & Bureau trees

### ISSUE THREAD

**Issue by Sesni** [Isenreik/HoI4-IR-Sanguinem-et-Lacrimis#93]
Hi, when I use Sanguinem et Lacrimas, I have found that all of the other tree don't work, and I'm stuck with the vanilla ones. I'm running only achievement compatible mods as well as all of the mods in the collection Araxiel's Modular Mods Menagerie other Ariaxel's Cheeki Breeki. My operating system is windows 10. I hope you keep making this mod: I would love to see it work properly.

**Comment by Araxiel** [comment]
This might be a bit late, but have to check the compatibility file.

Sounds like a conflicting Tech Tree issue.
